name: simple_dashboard
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/SimonWang9610/simple_dashboard.git

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.8
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
